services:
  postgres:
    container_name: 'postgres'
    image: "postgres:17.7"
    env_file:
      - .env
    restart: 'always'
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main
  app:
    image: "app:latest"
    build:
      context: .
    container_name: 'app'
    ports:
      - "8000:8000"
    volumes:
      - type: 'bind'
        source: '.'
        target: '/code/'
    depends_on:
      - postgres
    networks:
      - main
    env_file:
      - .env
    environment:
      - DOCKER_CONTAINER=True
  redis:
    image: registry.sedrehgroup.ir/redis:latest
    container_name: redis
    restart: on-failure
    expose:
      - 6379
    volumes:
      - redis_data:/bitnami/redis/data
    networks:
      - main
    env_file:
      - .env

networks:
  main:

volumes:
  db_data:
  redis_data:
